package org.itson.pruebas.listacomprapresentacion.presentacion;

import DTOs.ClienteDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 * Frame que muestra la pantalla de menu de inicio.
 *
 * @author Víctor Encinas - 244821 , José Armenta - 247641 , José Huerta -
 * 245345.
 */
public class frmMenuInicio extends javax.swing.JFrame {

    private PantallaInicial pantallaInicial;
    private ClienteDTO cliente;

    /**
     * Método constructor que nos permite crear el frame y además recibe el
     * valor del frame principal y el cliente. Además inicializa el valor del
     * frame principal y el cliente.
     *
     * @param pantallaInicial Frame inicial.
     * @param cliente Cliente actual.
     */
    public frmMenuInicio(PantallaInicial pantallaInicial, ClienteDTO cliente) {
        this.pantallaInicial = pantallaInicial;
        this.cliente = cliente;
        initComponents();
        cargarComboBox();
        lblCerrarSesion();
    }

    /**
     * Permite cargar los datos del comboBox y además se genera un método oyente
     * al momento de presionar una opcion del comboBox. Uno permite abrir la
     * lista de compras y otro permite agregar una compra.
     */
    private void cargarComboBox() {
        cbxListaAcciones.addItem("Mi lista de compras");
        cbxListaAcciones.addItem("Añadir lista");

        cbxListaAcciones.addActionListener((ActionEvent e) -> {
            if (cbxListaAcciones.getSelectedIndex() == 0) {
                panelListaCompras listaCompras = new panelListaCompras(this, cliente);
                mostrarPanel(listaCompras);
            } else if (cbxListaAcciones.getSelectedIndex() == 1) {
                panelNombreLista nombreLista = new panelNombreLista(this, cliente);
                mostrarPanel(nombreLista);
            }
        });
    }

    /**
     * Permite agregarle acciones de botón a un label. Permite cerrar el frame
     * menuInicio y manda a la pantalla inicial, es decir, cerrar sesión.
     */
    private void lblCerrarSesion() {
        lblCerrarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblCerrarSesion.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                lblCerrarSesion.setBackground(Color.GRAY);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                lblCerrarSesion.setBackground(Color.WHITE);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                pantallaInicial.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * Permite que los paneles se muestren en este frame. Primero borra el panel
     * actual y luego repinta el nuevo panel.
     *
     * @param p Panel a pintar.
     */
    protected void mostrarPanel(JPanel p) {
        p.setSize(1024, 597);
        p.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbxListaAcciones = new javax.swing.JComboBox<>();
        lblCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 185));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(54, 7, 69));

        cbxListaAcciones.setBackground(new java.awt.Color(54, 7, 69));
        cbxListaAcciones.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        cbxListaAcciones.setForeground(new java.awt.Color(255, 255, 255));
        cbxListaAcciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbxListaAcciones.setFocusable(false);

        lblCerrarSesion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("Cerrar sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cbxListaAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxListaAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrarSesion))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 598, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 83, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxListaAcciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
