/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.pruebas.listacomprapresentacion.presentacion;

import DTOs.ClienteDTO;
import DTOs.CompraDTO;
import DTOs.ProductoDTO;
import com.mycompany.listacomprafiltroporcompra.FiltroPorCompra;
import com.mycompany.listacomprafiltroporcompra.IFiltroPorCompra;
import com.mycompany.listacompragestorcompras.GestorCompras;
import com.mycompany.listacompragestorcompras.IGestorCompras;
import com.mycompany.listacompragestorproductos.GestorProductos;
import com.mycompany.listacompragestorproductos.IGestorProductos;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class panelListaCompras extends javax.swing.JPanel {

    private frmMenuInicio menuInicio;
    private ClienteDTO cliente;
    private CompraDTO compra;
    private IGestorCompras gestorCompras;
    private IGestorProductos gestorProductos;
    private IFiltroPorCompra filtroCompra;

    /**
     * Creates new form panelListaCompras
     */
    public panelListaCompras(frmMenuInicio menuInicio, ClienteDTO cliente) {
        this.menuInicio = menuInicio;
        this.cliente = cliente;
        this.compra = new CompraDTO();
        this.gestorCompras = new GestorCompras();
        this.gestorProductos = new GestorProductos();
        this.filtroCompra = new FiltroPorCompra();
        initComponents();

        tblListaCompras.getTableHeader().setFont(new Font("MS Reference Sans Serif", Font.BOLD, 18));

        mostrarListaCompras();
        menuInicio.mostrarPanel(this);
    }

    private void mostrarListaCompras() {
        DefaultTableModel modelo = (DefaultTableModel) tblListaCompras.getModel();
        modelo.setRowCount(0);

        List<CompraDTO> listaComprasCliente = gestorCompras.obtenerComprasPorCliente(cliente.getId());
        if (listaComprasCliente != null) {
            listaComprasCliente.forEach(p -> modelo.addRow(new Object[]{p.getNombreCompra()}));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCompras = new javax.swing.JTable();
        btnVerLista = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 185));
        setMaximumSize(new java.awt.Dimension(1024, 597));

        tblListaCompras.setAutoCreateRowSorter(true);
        tblListaCompras.setBackground(new java.awt.Color(255, 255, 185));
        tblListaCompras.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        tblListaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lista de compras creadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaCompras);

        btnVerLista.setBackground(new java.awt.Color(254, 194, 58));
        btnVerLista.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnVerLista.setText("Ver lista de compras");
        btnVerLista.setFocusable(false);
        btnVerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(254, 194, 58));
        btnEliminar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnEliminar.setText("Borrar lista");
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 28)); // NOI18N
        jLabel1.setText("Lista de compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 439, 439)
                .addComponent(btnVerLista, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(387, 387, 387))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerLista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaActionPerformed
        int filaSeleccionada = tblListaCompras.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object[] datosFila = new Object[tblListaCompras.getColumnCount()];

            for (int i = 0; i < tblListaCompras.getColumnCount(); i++) {
                datosFila[i] = tblListaCompras.getValueAt(filaSeleccionada, i);
            }
            compra.setNombreCompra(datosFila[0].toString());
            CompraDTO compraSelec = gestorCompras.obtenerCompraPorNombreYCliente(compra.getNombreCompra(), cliente.getId());

            panelListaProductos agregarProducto = new panelListaProductos(menuInicio, compraSelec);
            menuInicio.mostrarPanel(agregarProducto);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una lista de compras", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnVerListaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblListaCompras.getSelectedRow();

        if (filaSeleccionada != -1) {
            Object[] datosFila = new Object[tblListaCompras.getColumnCount()];

            for (int i = 0; i < tblListaCompras.getColumnCount(); i++) {
                datosFila[i] = tblListaCompras.getValueAt(filaSeleccionada, i);
            }
            
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de borrar esta lista?", "Atención", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {    
                compra.setNombreCompra(datosFila[0].toString());
                CompraDTO compraSelec = gestorCompras.obtenerCompraPorNombreYCliente(compra.getNombreCompra(), cliente.getId());
                List<ProductoDTO> productosAsociados = filtroCompra.obtenerProductosFiltrarPorCompra(compraSelec.getId());
                for (ProductoDTO productoAsociado : productosAsociados) {
                    productoAsociado = gestorProductos.obtenerProductoPorCaracteristicas(productoAsociado.getNombre(), productoAsociado.getCategoria(), productoAsociado.isComprado(),
                            productoAsociado.getCantidad(), compraSelec.getId());
                    gestorProductos.eliminarProducto(productoAsociado.getId());
                }
                gestorCompras.eliminarCompra(compraSelec.getId());
                mostrarListaCompras();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una lista de compras", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaCompras;
    // End of variables declaration//GEN-END:variables
}
